SELECT RECEIPTS.STORE_NAME, USERS.ID, SUM(RECEIPTS.TOTAL_SPENT) as TOTAL_SPEND FROM RECEIPTS JOIN USERS ON RECEIPTS.USER_ID = USERS.ID GROUP BY RECEIPTS.STORE_NAME, USERS.ID ORDER BY TOTAL_SPEND DESC
LIMIT 5
